apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret-pod
  name: secret-pod
  namespace: secret
spec:
  containers:
  - command:
    - sleep
    - "4800"
    image: busybox:1.31.1
    name: secret-pod
    volumeMounts:
    - name: secret1
      mountPath: "/tmp/secret1"
      readOnly: true
  volumes:
  - name: secret1
    secret:
      secretName: secret1
  dnsPolicy: ClusterFirst
